databases:
  - name: budget-buddy
    databaseName: budget_buddy_hbit
    user: budget_buddy_hbit_user

services:
  - type: web
    name: budget-buddy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget-buddy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false